### ISSUE TITLE
Why can't a file system implement standard conforming directory stream operations without opendir?

### ISSUE THREAD

**Issue by asomers** [Sherlock-Holo/fuse3#28]
The docs at https://docs.rs/fuse3/0.2.1/fuse3/raw/trait.Filesystem.html#method.opendir say that a file system cannot " implement standard conforming directory stream operations in case the contents of the directory can change between opendir and releasedir".  Why is that?  Is the comment no longer accurate after fixing issue #12 ?

**Comment by Sherlock-Holo** [comment]
I think after merged #12, the doc is out of date
