### ISSUE TITLE
Requesting new minor release bump on crates.io

### ISSUE THREAD

**Issue by aarond10** [Sherlock-Holo/fuse3#54]
Would it be possible to bump the minor version to 0.5.2 and push it to crates.io? I have an project that is dependent on these changes and would love to be able to just refer to a stable crates.io release.

**Comment by Sherlock-Holo** [comment]
I think we need to bump to 0.6.0 because in previous PR, we have updated the nix dep version

**Comment by Sherlock-Holo** [comment]
0.6.0 is released
