### ISSUE TITLE
Problem with hard link support

### ISSUE THREAD

**Issue by KongzhangHao** [Sherlock-Holo/fuse3#59]
I found that when running `ln target_file link_file` in a mounted directory where `target_file` exists and `link_file` does not exist, it shows an error: `ln: failed to create hard link 'link_file' => 'target_file': No such file or directory`. When checking the log, it shows that `lookup(target_file)` and `lookup(link_file)` are called, while `lookup(target_file)` finds the inode and `lookup(link_file)` doesn't find anything, which is expected. But then it says because `link_file` doesn't exist, there is an ENOENT error, which is very weird. If I create a file called `link_file`, it shows the error: `ln: failed to create hard link 'link_file': file exists`. Also, `link()` in the `filesystem` trait is never called and the opcode for it is never received.

**Comment by Sherlock-Holo** [comment]
I update the memfs example, implement the `link` method, and check the hard link

the log reports

> 2023-01-15T04:43:21.974053Z DEBUG fuse3::raw::session: receive opcode FUSE_GETATTR
>     at src/raw/session.rs:349
> 
>   2023-01-15T04:43:21.974151Z DEBUG fuse3::raw::session: getattr unique 222 inode 3
>     at src/raw/session.rs:959
>     in fuse3::raw::session::fuse_getattr
>     in fuse3::raw::session::handle_getattr with request: Request { unique: 222, uid: 1000, gid: 1000, pid: 39849 }, in_header: fuse_in_header { len: 56, opcode: 3, unique: 222, nodeid: 3, uid: 1000, gid: 1000, pid: 39849, padding: 0 }
> 
>   2023-01-15T04:43:21.977295Z DEBUG fuse3::raw::session: receive opcode FUSE_LOOKUP
>     at src/raw/session.rs:349
> 
>   2023-01-15T04:43:21.977348Z DEBUG fuse3::raw::session: lookup unique 224 name "a" in parent 1
>     at src/raw/session.rs:850
>     in fuse3::raw::session::fuse_lookup
>     in fuse3::raw::session::handle_lookup with request: Request { unique: 224, uid: 1000, gid: 1000, pid: 39853 }, in_header: fuse_in_header { len: 42, opcode: 1, unique: 224, nodeid: 1, uid: 1000, gid: 1000, pid: 39853, padding: 0 }
> 
>   2023-01-15T04:43:21.977373Z DEBUG fuse3::raw::session: lookup response fuse_entry_out { nodeid: 2, generation: 0, entry_valid: 1, attr_valid: 1, entry_valid_nsec: 0, attr_valid_nsec: 0, attr: fuse_attr { ino: 2, size: 0, blocks: 0, atime: 0, mtime: 0, ctime: 0, atimensec: 0, mtimensec: 0, ctimensec: 0, mode: 16877, nlink: 0, uid: 0, gid: 0, rdev: 0, blksize: 0, padding: 0 } }
>     at src/raw/session.rs:871
>     in fuse3::raw::session::fuse_lookup
>     in fuse3::raw::session::handle_lookup with request: Request { unique: 224, uid: 1000, gid: 1000, pid: 39853 }, in_header: fuse_in_header { len: 42, opcode: 1, unique: 224, nodeid: 1, uid: 1000, gid: 1000, pid: 39853, padding: 0 }
> 
>   2023-01-15T04:43:21.977433Z DEBUG fuse3::raw::session: receive opcode FUSE_LOOKUP
>     at src/raw/session.rs:349
> 
>   2023-01-15T04:43:21.977475Z DEBUG fuse3::raw::session: lookup unique 226 name "123.txt" in parent 2
>     at src/raw/session.rs:850
>     in fuse3::raw::session::fuse_lookup
>     in fuse3::raw::session::handle_lookup with request: Request { unique: 226, uid: 1000, gid: 1000, pid: 39853 }, in_header: fuse_in_header { len: 48, opcode: 1, unique: 226, nodeid: 2, uid: 1000, gid: 1000, pid: 39853, padding: 0 }
> 
>   2023-01-15T04:43:21.977498Z DEBUG fuse3::raw::session: lookup response fuse_entry_out { nodeid: 4, generation: 0, entry_valid: 1, attr_valid: 1, entry_valid_nsec: 0, attr_valid_nsec: 0, attr: fuse_attr { ino: 4, size: 4, blocks: 0, atime: 0, mtime: 0, ctime: 0, atimensec: 0, mtimensec: 0, ctimensec: 0, mode: 33188, nlink: 0, uid: 0, gid: 0, rdev: 0, blksize: 0, padding: 0 } }
>     at src/raw/session.rs:871
>     in fuse3::raw::session::fuse_lookup
>     in fuse3::raw::session::handle_lookup with request: Request { unique: 226, uid: 1000, gid: 1000, pid: 39853 }, in_header: fuse_in_header { len: 48, opcode: 1, unique: 226, nodeid: 2, uid: 1000, gid: 1000, pid: 39853, padding: 0 }
> 
>   2023-01-15T04:43:21.977559Z DEBUG fuse3::raw::session: receive opcode FUSE_LOOKUP
>     at src/raw/session.rs:349
> 
>   2023-01-15T04:43:21.977601Z DEBUG fuse3::raw::session: lookup unique 228 name "bbb.txt" in parent 3
>     at src/raw/session.rs:850
>     in fuse3::raw::session::fuse_lookup
>     in fuse3::raw::session::handle_lookup with request: Request { unique: 228, uid: 1000, gid: 1000, pid: 39853 }, in_header: fuse_in_header { len: 48, opcode: 1, unique: 228, nodeid: 3, uid: 1000, gid: 1000, pid: 39853, padding: 0 }

that's so strange, when running `ln a b`, kernel expect b should be exists

**Comment by KongzhangHao** [comment]
I did some investigation and the problem seems to be with `linkat()` called by the kernel (i.e., `linkat(AT_FDCWD, "../a/123.txt", AT_FDCWD, "bbb.txt", 0) = -1 ENOENT (没有那个文件或目录)` in the above strace log). In the linux implementation of `linkat` (https://elixir.bootlin.com/linux/v6.2-rc3/source/fs/namei.c#L4553), it calls `filename_lookup` on target file and `filename_create` on the link file. Both `filename_lookup` and `filename_create` call `lookup`, but they are with different flags (`filename_create` has an additional flag `LOOKUP_CREATE`). Is it possible that they are calling lookup with different flags but fuse3 cannot receive that?

**Comment by asomers** [comment]
FWIW link works for me.

**Comment by Sherlock-Holo** [comment]
> FWIW link works for me.

I think the problem should occur in the `Filesystem` implement, as @KongzhangHao says maybe the `lookup` implement should check the flags to distinguish the normal lookup and the link lookup?

**Comment by KongzhangHao** [comment]
It seems that the `lookup` function in the `FileSystem` trait doesn't have flag in its interface. Is it because the fuse3 binary doesn't support flags in its `lookup` interface?

**Comment by asomers** [comment]
What binary?  This crate does not involve any such thing.  There isn't any `flags` field because the FUSE protocol does not include any such field in the FUSE_LOOKUP operation.  The only thing that the fuse server gets during a lookup is the parent's node id and the file name.

**Comment by Sherlock-Holo** [comment]
in the example memfs, the reason for the hard link error is the `nlink` filed is incorrect which return by `lookup` implement,
I modify the memfs example https://github.com/Sherlock-Holo/fuse3/pull/61 and test success on my computer
@KongzhangHao could you check your `Filesystem`, is the nlink correct?

**Comment by KongzhangHao** [comment]
I fixed the nlink and it is working perfectly. Thanks for your help!
