### ISSUE TITLE
question: duplicate generation entry in ReplyEntry

### ISSUE THREAD

**Issue by majewsky** [Sherlock-Holo/fuse3#63]
In [`fuse3::raw::reply::ReplyEntry`](https://docs.rs/fuse3/0.6.1/fuse3/raw/reply/struct.ReplyEntry.html), there are two separate fields for a generation number: `reply.generation` and `reply.attr.generation`. Is there a difference between them that should be documented? If not, the `reply.generation` field could potentially be removed.

**Comment by Sherlock-Holo** [comment]
I think the `FileAttr.generation` can be removed

[libfuse](https://sourcegraph.com/github.com/libfuse/libfuse@3f65bb699cd2f0afe2b9519c39d29922229f2168/-/blob/include/fuse_kernel.h) `fuse_attr` struct doesn't contain the `generation` field

**Comment by Sherlock-Holo** [comment]
#69 will remove the useless `FileAttr.generation` field
