### ISSUE TITLE
Unused const `FUSE_WRITE_CACHE`

### ISSUE THREAD

**Issue by KongzhangHao** [Sherlock-Holo/fuse3#65]
The function documentation of `write_back()` in file `//src/mount_options.rs` says that the write flag `FUSE_WRITE_CACHE` should be enabled to use the write back cache for buffered writes. However, it seems that flag `FUSE_WRITE_CACHE` in file `//src/raw/abi.rs` doesn't appear referenced anywhere else except in this comment. I'm wondering how this actually works to enable the write buffer?

**Comment by Sherlock-Holo** [comment]
that's a doc bug, when enable the `write_back` feature, the `FUSE_WRITEBACK_CACHE` flag is set, not `FUSE_WRITE_CACHE`

`FUSE_WRITE_CACHE` is used to determine whether the write operation is a delay write or not

**Comment by Sherlock-Holo** [comment]
#67 #68 fix the doc and add `write_flags`
